module.exports = {
  apps: [
    {
      name: "silicon-nexus",
      script: "dist/server.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
        HOST: "127.0.0.1",
        APP_URL: "https://silinex.xyz",
      },
      error_file: "./logs/err.log",
      out_file: "./logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "silicon-nexus-feed-daily",
      script: "npx",
      args: "tsx scripts/feed-daily.ts",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: false,
      watch: false,
      cron_restart: "15 1 * * *",
      env: {
        NODE_ENV: "production",
        APP_URL: "https://silinex.xyz",
        FEED_HN_LIMIT: "8",
      },
      error_file: "./logs/feed-err.log",
      out_file: "./logs/feed-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "silicon-nexus-geo-daily",
      script: "npx",
      args: "tsx scripts/geo-daily.ts",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: false,
      watch: false,
      cron_restart: "30 1 * * *",
      env: {
        NODE_ENV: "production",
        APP_URL: "https://silinex.xyz",
      },
      error_file: "./logs/geo-err.log",
      out_file: "./logs/geo-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "silicon-nexus-backup-daily",
      script: "npx",
      args: "tsx scripts/backup-sqlite.ts",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: false,
      watch: false,
      cron_restart: "5 2 * * *",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/backup-err.log",
      out_file: "./logs/backup-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "silicon-nexus-worker",
      script: "npx",
      args: "tsx scripts/hub-worker.ts",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        APP_URL: "https://silinex.xyz",
        NEXUS_WORKER_INTERVAL_MS: "2000",
      },
      error_file: "./logs/worker-err.log",
      out_file: "./logs/worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
